In [2]:
import numpy as np

In [8]:
lista = [1,2,3]
array = np.array(lista)

In [9]:
array

array([1, 2, 3])

In [10]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
np.ones(shape=(10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
    aleatorios = np.random.randint(0,100, 50)

In [17]:
aleatorios

array([78, 16, 25, 53,  0, 79, 25, 13, 41, 26, 37, 38, 18, 83, 10, 35, 27,
       12, 65, 12, 69, 47, 39, 74, 97, 85, 40,  6, 71, 79, 14, 78, 43, 17,
       95, 35, 65, 73, 95, 47, 93, 63, 53, 86, 50, 49, 45, 15, 35, 42])

In [20]:
aleatorios.min()

0

In [23]:
aleatorios = aleatorios.reshape(5, 10)

In [25]:
aleatorios

array([[78, 16, 25, 53,  0, 79, 25, 13, 41, 26],
       [37, 38, 18, 83, 10, 35, 27, 12, 65, 12],
       [69, 47, 39, 74, 97, 85, 40,  6, 71, 79],
       [14, 78, 43, 17, 95, 35, 65, 73, 95, 47],
       [93, 63, 53, 86, 50, 49, 45, 15, 35, 42]])