In [1]:
import numpy as np

In [2]:
lista = [1,2,3,4,5,6,5] #una lista de valores en python 

In [3]:
lista

[1, 2, 3, 4, 5, 6, 5]

In [5]:
arreglo = np.array(lista)

In [6]:
arreglo

array([1, 2, 3, 4, 5, 6, 5])

In [7]:
arreglo[0]

1

In [13]:
arreglo[6]

5

In [15]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
ale = np.random.randint(0, 69, 50)

In [20]:
ale

array([15, 42, 26, 40, 33, 18, 62, 56, 45, 56, 68,  7, 20, 39, 33, 20, 37,
       68, 48, 40,  3, 58, 24, 20, 48,  3, 43, 63, 54, 26, 46, 42, 35, 60,
       29, 32, 50, 61, 66, 36, 60, 61, 32, 39, 59, 31, 13, 65, 39, 27])

In [21]:
ale.max()

68

In [22]:
ale.min()

3

In [23]:
ale.argmax()

10

In [24]:
ale.argmin()

20

In [25]:
ale = ale.reshape(5,10)

In [26]:
ale

array([[15, 42, 26, 40, 33, 18, 62, 56, 45, 56],
       [68,  7, 20, 39, 33, 20, 37, 68, 48, 40],
       [ 3, 58, 24, 20, 48,  3, 43, 63, 54, 26],
       [46, 42, 35, 60, 29, 32, 50, 61, 66, 36],
       [60, 61, 32, 39, 59, 31, 13, 65, 39, 27]])

In [27]:
ale = ale.reshape(2,25)